language: ruby
install: bundle install --jobs=3 --retry=3 --no-deployment
script:
- bundle exec rake assets:precompile
- bundle exec rspec spec/features/
deploy:
  provider: heroku
  api_key:
    secure: JHaaojmt64klUFQElkjE0arLV02cumMH0oDinvdRnnbMGCQVNJwTq8jlv9o1n9DctUDk+BvYJCU6B0cZHvqDlWgkZOR8VvXlaO644AmGKkCLEW1/6FCjEAitLkiRZ04kkGgVpDq5spcPDmjhSznYlUdonVgXq55M3IV3Yt+9GmU=
  on:
    branch: master
  app: railsguides-jp
notifications:
  webhooks:
    secure: HFPm4OWPWKheXFkRLZIlJckLEjZ8eW9a5o/dEZoeKQFjrK2kGrBDft4Xp6aKuqJmv4g/VoDDG5x9ZwTDNAxT4u4q2YbXikkmIFbLsc7cQz4hywXRbkWOTKZHaIdorLF0eZnxPybEVZCflH7LopyobwrBo/KC9SLnn7IUnalCwvg=
