language: ruby
rvm:
- 2.3.3
sudo: false
script:
- bundle exec rake assets:precompile
- bundle exec rspec spec/features/
deploy:
  provider: heroku
  api_key:
    secure: c0PPn1m2dQ3OUk0/34F+wBnB8K8+IgAQ2h2ydPbTNeqa+AYM50PZfQ2lo9YjcHfBtXCf8s9u2QDE8xBXaTOQtRulp0tuP+DcQv/Pw0aujBbb1UFTdHNqos3rD29ywByEj4xI1FNO+ElN4MK9NRawuSAFZ9rcJ3bRO7VV4mZitus=
  on: japanese
  app:
    master: railsguides-jp
