name: actions
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: ☑️ Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: 💎 Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: 🔧 Build & Test
        run: |
          bundle exec rake assets:precompile
          bundle exec rake test 

      - name: ✅ Check YAML format
        run: |
          bundle exec rake yasslab:test
